import * as THREE from 'three';

const canvas=document.getElementById('game');
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x07131f); scene.fog=new THREE.Fog(0x07131f,45,150);
const camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.05,500);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;
scene.add(new THREE.HemisphereLight(0x9fdcff,0x16202b,1.6));const sun=new THREE.DirectionalLight(0xffe6b5,2.2);sun.position.set(-30,50,20);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
const world=new THREE.Group();scene.add(world);
const mats={platform:new THREE.MeshStandardMaterial({color:0x257b52,roughness:.8}),wall:new THREE.MeshStandardMaterial({color:0x3a4650,roughness:.9}),key:new THREE.MeshStandardMaterial({color:0xffd75a,emissive:0x684400,emissiveIntensity:.7,metalness:.3,roughness:.25}),checkpoint:new THREE.MeshStandardMaterial({color:0x40c9ff,emissive:0x0b5068,emissiveIntensity:.7}),hazard:new THREE.MeshStandardMaterial({color:0xe83a54,emissive:0x530a14,emissiveIntensity:.8}),enemy:new THREE.MeshStandardMaterial({color:0xb33e55,roughness:.6}),door:new THREE.MeshStandardMaterial({color:0x7b5b3e,roughness:.75}),goal:new THREE.MeshStandardMaterial({color:0x72dfff,emissive:0x0f708b,emissiveIntensity:1.2})};
const geo={box:(x,y,z)=>new THREE.BoxGeometry(x,y,z),sphere:(r)=>new THREE.SphereGeometry(r,16,12),cyl:(r,h)=>new THREE.CylinderGeometry(r,r,h,16)};
const sceneObjects=[];let selected=null,tool='move',gameMode='menu';
const keys={};let jumpQueued=false;
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Space'){jumpQueued=true;e.preventDefault()} if(gameMode==='editor'){if(e.code==='Digit1')setTool('select');if(e.code==='Digit2')setTool('move');if(e.code==='Digit3')setTool('scale');if(e.code==='Delete')deleteSelected();if((e.ctrlKey||e.metaKey)&&e.code==='KeyD')duplicateSelected();if(e.code==='KeyF')focusSelected()}else if(e.code==='Escape'&&gameMode==='play')setMode('menu')});addEventListener('keyup',e=>keys[e.code]=false);
function meshFor(o){const [w,h,d]=o.size;let m;if(o.type==='key'){m=new THREE.Mesh(geo.cyl(.25,.8),mats.key);m.rotation.z=.35}else if(o.type==='checkpoint'){m=new THREE.Mesh(geo.cyl(.45,.25),mats.checkpoint)}else if(o.type==='enemy'){m=new THREE.Mesh(geo.sphere(.55),mats.enemy)}else if(o.type==='goal'){m=new THREE.Mesh(geo.cyl(.8,1.8),mats.goal)}else{m=new THREE.Mesh(geo.box(w,h,d),mats[o.type]||mats.platform)}m.position.set(...o.pos);m.castShadow=true;m.receiveShadow=true;m.userData.editorId=o.id;return m}
function addObject(type='platform',pos=[0,.5,0],size=type==='key'||type==='checkpoint'||type==='enemy'||type==='goal'?[1,1,1]:[6,1,6]){const o={id:crypto.randomUUID(),type,pos:[...pos],size:[...size],name:type.toUpperCase()};sceneObjects.push(o);world.add(meshFor(o));refreshExplorer();selectObject(o.id);return o}
function rebuildWorld(){while(world.children.length)world.remove(world.children[0]);for(const o of sceneObjects)world.add(meshFor(o));if(gameMode==='play')createPlayer()}
function getObject(id){return sceneObjects.find(o=>o.id===id)}
const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2();
function screenRay(e){const r=canvas.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;raycaster.setFromCamera(mouse,camera)}
const outline=new THREE.LineSegments();outline.material=new THREE.LineBasicMaterial({color:0x6ff3ff,transparent:true,opacity:.95});outline.visible=false;scene.add(outline);
function updateOutline(){if(!selected){outline.visible=false;return}const o=getObject(selected.id);if(!o){outline.visible=false;return}outline.geometry=new THREE.EdgesGeometry(new THREE.BoxGeometry(Math.max(o.size[0],.7),Math.max(o.size[1],.3),Math.max(o.size[2],.7)));outline.position.set(...o.pos);outline.visible=true}
function selectObject(id){selected=id?getObject(id):null;refreshExplorer();renderInspector();updateOutline()}
function refreshExplorer(){const box=document.getElementById('objects');box.innerHTML='';sceneObjects.forEach(o=>{const d=document.createElement('div');d.className='object'+(selected?.id===o.id?' sel':'');d.textContent=o.name+'  '+o.id.slice(0,4);d.onclick=()=>selectObject(o.id);box.appendChild(d)})}
function renderInspector(){const body=document.getElementById('inspectorBody');if(!selected){body.textContent='Select an object.';return}const o=selected;body.innerHTML='';for(const group of [['X',0,'pos'],['Y',1,'pos'],['Z',2,'pos'],['W',0,'size'],['H',1,'size'],['D',2,'size']]){const [label,i,k]=group;const row=document.createElement('div');row.className='field';row.innerHTML=`<label>${label}</label><input type="number" step="0.25" value="${o[k][i]}">`;row.querySelector('input').onchange=e=>{o[k][i]=Number(e.target.value)||0;rebuildWorld();selectObject(o.id)};body.appendChild(row)} }
function deleteSelected(){if(!selected)return;const i=sceneObjects.findIndex(o=>o.id===selected.id);if(i>=0)sceneObjects.splice(i,1);selected=null;rebuildWorld();refreshExplorer();renderInspector();updateOutline()}
function duplicateSelected(){if(!selected)return;const o=getObject(selected.id);const n={...o,id:crypto.randomUUID(),name:o.name+' COPY',pos:[o.pos[0]+1,o.pos[1],o.pos[2]+1],size:[...o.size]};sceneObjects.push(n);rebuildWorld();selectObject(n.id)}
function focusSelected(){if(!selected)return;camera.position.set(selected.pos[0]+8,selected.pos[1]+6,selected.pos[2]+8);editorTarget.set(...selected.pos)}
function setTool(t){tool=t;document.querySelectorAll('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));}

let yaw=.7,pitch=.35,editorTarget=new THREE.Vector3(0,0,0),camDist=24;let orbiting=false,lastX=0,lastY=0;
canvas.addEventListener('mousedown',e=>{if(gameMode!=='editor')return;if(e.button===0||e.button===2){screenRay(e);const hits=raycaster.intersectObjects(world.children,false);if(hits[0]){selectObject(hits[0].object.userData.editorId);dragging=tool==='move'||tool==='scale';dragStart={x:e.clientX,y:e.clientY,o:selected?getObject(selected.id):null,base:selected?{pos:[...selected.pos],size:[...selected.size]}:null}}else{orbiting=true;lastX=e.clientX;lastY=e.clientY}}});canvas.addEventListener('contextmenu',e=>e.preventDefault());
let dragging=false,dragStart=null;addEventListener('mouseup',()=>{dragging=false;orbiting=false});addEventListener('mousemove',e=>{if(gameMode!=='editor')return;if(orbiting){yaw-=(e.clientX-lastX)*.006;pitch-= (e.clientY-lastY)*.005;pitch=Math.max(-1.4,Math.min(1.4,pitch));lastX=e.clientX;lastY=e.clientY}else if(dragging&&selected){const o=getObject(selected.id);if(tool==='move'){const dx=(e.clientX-dragStart.x)*.03, dz=(e.clientY-dragStart.y)*.03;o.pos[0]=snap(dragStart.base.pos[0]+dx);o.pos[2]=snap(dragStart.base.pos[2]+dz)}else if(tool==='scale'){o.size[0]=Math.max(.5,snap(dragStart.base.size[0]+(e.clientX-dragStart.x)*.03));o.size[2]=Math.max(.5,snap(dragStart.base.size[2]-(e.clientY-dragStart.y)*.03))}rebuildWorld();selectObject(o.id)}});
function snap(v){const n=Number(document.getElementById('snap')?.value||1);return Math.round(v/n)*n}
addEventListener('wheel',e=>{if(gameMode==='editor'){camDist=Math.max(5,Math.min(80,camDist+e.deltaY*.02))}});
function updateEditorCamera(dt){const sp=(keys.ShiftLeft||keys.ShiftRight?24:12)*dt;const forward=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw));const right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));if(keys.KeyW)editorTarget.addScaledVector(forward,sp);if(keys.KeyS)editorTarget.addScaledVector(forward,-sp);if(keys.KeyA)editorTarget.addScaledVector(right,-sp);if(keys.KeyD)editorTarget.addScaledVector(right,sp);if(keys.KeyQ)editorTarget.y-=sp;if(keys.KeyE)editorTarget.y+=sp;camera.position.set(editorTarget.x+Math.sin(yaw)*Math.cos(pitch)*camDist,editorTarget.y+Math.sin(pitch)*camDist,editorTarget.z+Math.cos(yaw)*Math.cos(pitch)*camDist);camera.lookAt(editorTarget);updateOutline()}

let player=null;const p={vel:new THREE.Vector3(),half:new THREE.Vector3(.42,.9,.42),grounded:false,yaw:0};
function findSpawn(){const marker=sceneObjects.find(o=>o.type==='checkpoint');if(marker){const top=groundAt(marker.pos[0],marker.pos[2],Infinity);return {x:marker.pos[0],z:marker.pos[2],y:(top>-998?top:marker.pos[1])+p.half.y+0.05}}const start=sceneObjects.find(o=>o.type==='platform');if(start){const b=aabb(start);return {x:start.pos[0],z:start.pos[2],y:b.maxY+p.half.y+0.05}}return {x:0,z:0,y:1.0+p.half.y}}
function createPlayer(){if(player)scene.remove(player);player=new THREE.Group();const body=new THREE.Mesh(geo.box(.8,1.8,.8),new THREE.MeshStandardMaterial({color:0x6adfff,emissive:0x0b5066,emissiveIntensity:.25}));body.position.y=.9;body.castShadow=true;player.add(body);scene.add(player);const spawn=findSpawn();player.position.set(spawn.x,spawn.y,spawn.z);p.vel.set(0,0,0);p.grounded=true}
function solids(){return sceneObjects.filter(o=>['platform','wall','door'].includes(o.type))}
function aabb(o){return {minX:o.pos[0]-o.size[0]/2,maxX:o.pos[0]+o.size[0]/2,minY:o.pos[1]-o.size[1]/2,maxY:o.pos[1]+o.size[1]/2,minZ:o.pos[2]-o.size[2]/2,maxZ:o.pos[2]+o.size[2]/2}}
function collidesAt(x,z){for(const o of solids()){const b=aabb(o);if(x+p.half.x>b.minX&&x-p.half.x<b.maxX&&player.position.y+p.half.y>b.minY&&player.position.y-p.half.y<b.maxY&&z+p.half.z>b.minZ&&z-p.half.z<b.maxZ)return o}return null}
function groundAt(x,z,y){let top=-999;for(const o of solids()){const b=aabb(o);if(x+p.half.x>b.minX&&x-p.half.x<b.maxX&&z+p.half.z>b.minZ&&z-p.half.z<b.maxZ&&b.maxY<=y+.2&&b.maxY>top)top=b.maxY}return top}
function startPlay(){setMode('play');sceneObjects.filter(o=>o.type==='key').forEach(o=>o.collected=false);createPlayer();camera.position.set(player.position.x,player.position.y+4,player.position.z+8);camera.lookAt(player.position.x,player.position.y+1,player.position.z)}
function updatePlay(dt){if(!player)return;const f=new THREE.Vector3(0,0,-1).applyAxisAngle(new THREE.Vector3(0,1,0),0);const ix=(keys.KeyD?1:0)-(keys.KeyA?1:0),iz=(keys.KeyS?1:0)-(keys.KeyW?1:0);const dir=new THREE.Vector3(ix,0,iz);if(dir.lengthSq()>0)dir.normalize();const speed=(keys.ShiftLeft||keys.ShiftRight)?10:6;player.position.x+=dir.x*speed*dt; if(collidesAt(player.position.x,player.position.z))player.position.x-=dir.x*speed*dt;player.position.z+=dir.z*speed*dt;if(collidesAt(player.position.x,player.position.z))player.position.z-=dir.z*speed*dt;if(jumpQueued&&p.grounded){p.vel.y=10;jumpQueued=false;p.grounded=false}jumpQueued=false;p.vel.y-=25*dt;player.position.y+=p.vel.y*dt;const g=groundAt(player.position.x,player.position.z,player.position.y);if(g>-998&&p.vel.y<=0&&player.position.y-p.half.y<=g){player.position.y=g+p.half.y;p.vel.y=0;p.grounded=true}else p.grounded=false;if(player.position.y<-20){const spawn=findSpawn();player.position.set(spawn.x,spawn.y,spawn.z);p.vel.set(0,0,0);p.grounded=true}camera.position.lerp(new THREE.Vector3(player.position.x,player.position.y+4,player.position.z+8),1-Math.exp(-6*dt));camera.lookAt(player.position.x,player.position.y+1,player.position.z);for(const o of sceneObjects){if(o.type==='key'&&!o.collected&&player.position.distanceTo(new THREE.Vector3(...o.pos))<1.6){o.collected=true;world.children.find(m=>m.userData.editorId===o.id)?.visible=false;toast('KEY COLLECTED')}}}
function setMode(m){gameMode=m;document.getElementById('menu').classList.toggle('hidden',m!=='menu');document.getElementById('hud').classList.toggle('hidden',m!=='play');document.getElementById('studioUI').classList.toggle('hidden',m!=='editor');if(m==='editor'){camera.position.set(18,14,18);camera.lookAt(0,0,0);refreshExplorer();setTool('move')}if(m==='play')startUi()}
function startUi(){document.getElementById('keysTotal').textContent=sceneObjects.filter(o=>o.type==='key').length}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.style.opacity=1;setTimeout(()=>x.style.opacity=0,1200)}
function newLevel(){sceneObjects.length=0;addObject('platform',[0,0,0],[14,1,14]);addObject('checkpoint',[0,0.55,4],[1,0.25,1]);addObject('platform',[0,1.25,-8],[8,1,8]);addObject('key',[0,1.9,-8]);addObject('platform',[0,2.5,-16],[8,1,8]);addObject('door',[0,4,-21],[5,4,1]);addObject('platform',[0,3.75,-24],[10,1,8]);addObject('goal',[0,5.15,-27]);selectObject(null);rebuildWorld()}
function exportJSON(){return JSON.stringify({version:1,objects:sceneObjects.map(o=>({...o,pos:[...o.pos],size:[...o.size]}))},null,2)}
document.getElementById('play').onclick=()=>startPlay();document.getElementById('studio').onclick=()=>setMode('editor');document.getElementById('how').onclick=()=>document.getElementById('howPanel').classList.remove('hidden');document.getElementById('closeHow').onclick=()=>document.getElementById('howPanel').classList.add('hidden');document.getElementById('menuBtn').onclick=()=>setMode('menu');document.getElementById('playLevel').onclick=()=>startPlay();document.getElementById('newLevel').onclick=()=>newLevel();document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addObject(b.dataset.add,[editorTarget.x,Math.max(0,editorTarget.y),editorTarget.z]));document.getElementById('deleteObj').onclick=deleteSelected;document.getElementById('duplicateObj').onclick=duplicateSelected;document.getElementById('copyJSON').onclick=()=>navigator.clipboard.writeText(exportJSON()).then(()=>toast('JSON COPIED'));document.getElementById('downloadJSON').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([exportJSON()],{type:'application/json'}));a.download='skybound-level.json';a.click();URL.revokeObjectURL(a.href)};document.getElementById('loadJSON').onclick=()=>{try{const x=JSON.parse(document.getElementById('jsonBox').value);sceneObjects.length=0;x.objects.forEach(o=>sceneObjects.push({...o}));rebuildWorld();selectObject(null);toast('LEVEL LOADED')}catch(e){toast('INVALID JSON')}};
newLevel();
let last=performance.now();function loop(t){const dt=Math.min(.033,(t-last)/1000);last=t;if(gameMode==='editor')updateEditorCamera(dt);if(gameMode==='play')updatePlay(dt);renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
